### ISSUE TITLE
Reference for breaking changes between 1.x and 2.x?

### ISSUE THREAD

**Issue by SeanKilleen** [nblumhardt/autofac-serilog-integration#18]
Hi @nblumhardt,

Love this integration and am just trying to figure out which version to implement. 

We currently have Autofac `v3.5.2` in our project and haven't made the leap to `4.x` yet (though it's on my list).

Is there anything I should be aware of related to [v1.0.15 of this package](http://www.nuget.org/packages/AutofacSerilogIntegration/1.0.15) as opposed to [v2.0.0](http://www.nuget.org/packages/AutofacSerilogIntegration/2.0.0) which depends on Autofac v4? I couldn't find release notes anywhere, but I might not be looking in the correct place.

**Comment by nblumhardt** [comment]
Hi Sean!

I think the only difference currently between the 1.x and 2.x versions of this package is the Autofac version and the .NET Core support that comes with it.

PR #14 on Jan 20 was the switch-over point - there have only been a couple of tooling-related commits since then: https://github.com/nblumhardt/autofac-serilog-integration/commits/dev

Hope this helps,
Nick

**Comment by SeanKilleen** [comment]
👍 Totally answers my question. Thanks!
