### ISSUE TITLE
(Global) logger prematurely disposed when ILogger is resolved directly from a child lifetime scope

### ISSUE THREAD

**Issue by nblumhardt** [nblumhardt/autofac-serilog-integration#3]

**Comment by srogovtsev** [comment]
I think this still happens if you use `RegisterLogger(builder, logger, dispose: true)`. I think that the issue is that `LoggerProvider` is registered per-dependency instead of singleton:

```
builder.Register(c =>
                {
                    LoggerProvider provider = new LoggerProvider(_logger);
                    return provider;
                })
                    .AsSelf()
                    .AutoActivate()
                    .OnRelease(c => c.Release());
```
(https://github.com/nblumhardt/autofac-serilog-integration/blob/dev/src/AutofacSerilogIntegration/ContextualLoggingModule.cs#L44)

**Comment by nblumhardt** [comment]
Thanks @srogovtsev - I think you're right 👍

**Comment by srogovtsev** [comment]
I think I can take this, but there's one thing I'd like to understand: is there any reason you don't want `LoggerProvider` to be single-instance?

(actually, this mirrors the Microsoft.Extensions.Logging integration, where it _is_ single-instance)

**Comment by nblumhardt** [comment]
I think single-instance would be correct, here (though it's been a while since I've worked in this codebase...). Thanks for the offer of help! :+1:
